services:
  warehouse-sync:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: warehouse_sync_service
    environment:
      - KAFKA_BROKER=kafka:9092
      - DATABASE_URL=postgres://user:pass@postgres:5432/inventory
    depends_on:
      - kafka
      - postgres
    restart: on-failure
    networks:
      - backend

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
