name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build ./...
      - name: Run tests
        run: |
          if go test ./...; then
            echo "Tests passed"
          else
            echo "Tests failed"
            exit 1
          fi
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run integration tests with Docker Compose
        run: docker-compose -f .github/workflows/docker-compose.yml up --build --abort-on-container-exit --exit-code-from test
